# embed_spirv.cmake — Generate C++ header with embedded SPIR-V bytecode arrays.
#
# Usage: cmake -DOUTPUT=<output.h> -DSPIRV_DIR=<dir> -P embed_spirv.cmake

file(GLOB_RECURSE SPV_FILES "${SPIRV_DIR}/*.spv")

set(ENTRIES "")
foreach(SPV ${SPV_FILES})
    file(RELATIVE_PATH REL "${SPIRV_DIR}" ${SPV})
    # Convert path to C identifier
    string(REPLACE "/" "_" IDENT ${REL})
    string(REPLACE "." "_" IDENT ${IDENT})
    string(REPLACE "-" "_" IDENT ${IDENT})

    # Read file size
    file(SIZE ${SPV} FILE_SIZE)

    # Read binary as hex string
    file(READ ${SPV} HEX_BYTES HEX)

    # Format: 0xNN, 0xNN, ... (16 bytes per line)
    string(REGEX REPLACE "(..)" "0x\\0," FORMATTED "${HEX_BYTES}")

    string(APPEND ENTRIES "static const uint8_t kShader_${IDENT}[] = {\n${FORMATTED}};\n")
    string(APPEND ENTRIES "static const size_t kShader_${IDENT}_size = ${FILE_SIZE};\n\n")
endforeach()

file(WRITE ${OUTPUT}
"// Auto-generated by cmake/embed_spirv.cmake — DO NOT EDIT\n"
"#pragma once\n"
"#include <cstdint>\n"
"#include <cstddef>\n\n"
"namespace noix::video {\n\n"
"${ENTRIES}"
"} // namespace noix::video\n"
)
